### ISSUE TITLE
Trouble building under VS 2015

### ISSUE THREAD

**Issue by mtlynch** [Dainius14/twinder#1]
Thanks for creating this! I'm having trouble building from source under VS Professional 2015:

>The type or namespace name 'BinaryAnalysis' could not be found (are you missing a using directive or an assembly reference?)

>The type or namespace name 'Maps' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)

>The type or namespace name 'Location' could not be found (are you missing a using directive or an assembly reference?)

>'string' does not contain a definition for 'Unidecode' and no extension method 'Unidecode' accepting a first argument of type 'string' could be found (are you missing a using directive or an assembly reference?)

**Comment by Dainius14** [comment]
For the Maps you need [Bing Maps for Devs](https://www.microsoft.com/en-us/download/details.aspx?displaylang=en&id=27165) installed and then add it to references manually. 
Also add a ref to UnidecodeSharp.dll, which is in bin folder.
For Location add System.Device namespace.

Is there a way to include these in the source code, or will other people always have to include these things by hand?

**Comment by mtlynch** [comment]
Thanks for the quick response!

Errors about "Maps" and "Location" went away after installing the Bing Maps SDK. It'd be good to mention in the README that developers need to install that SDK before attempting to build from source.

PR #5 should fix the issues about Unidecode.

I'm still seeing errors for `BinaryAnalysis`. Which library is that?

Edit: Nevermind. `BinaryAnalysis` is the old version of Unidecode. I updated the PR to remove that.
