### ISSUE TITLE
Binding not working RecommendationsView

### ISSUE THREAD

**Issue by sleinert** [Dainius14/twinder#10]
This `DistanceKilometers` variable does not exist, you could atleast show the miles now, but I saw some code for converting the miles to km, so perhaps you were aware.

[Line 101](https://github.com/Dainius14/twinder/blob/e5b34cc00979d14ae84d082c8b1ead7937f71a73/View/RecommendationsView.xaml#L101)

**Comment by Dainius14** [comment]
Yes, Tinder only gives miles. I used to multiply it by 1.6 in the model, but then I thought to do it another and then I probably forgot it lol.
Now I'm reworking chat UI. After I do that I'll get to reworking recommendations UI and match UI, they are buggy,don't show all the info and are overall inconsistent.

**Comment by sleinert** [comment]
Ah ok good to know :)
