### ISSUE TITLE
Unsafe method EmptyRecommendations

### ISSUE THREAD

**Issue by sleinert** [Dainius14/twinder#9]
I believe this method was triggered since this seems the most likely culprit. The program tried to delete my entire C drive basically. I started the program and the GUI was basically 'empty' and stuck ( I think the tinder rate_limit code was triggered), shortly after that I saw some folders disappearing from my desktop so I killed it from taskmngr. After that I looked under AppData and my user folder and saw that most things were deleted. Not much harm done since I could recover it, I would recommend you add some code to check the directory paths.

Apart from that great idea to create such an App :)

**Comment by Dainius14** [comment]
Wow. Really sorry for that. I will look at this asap

**Comment by Dainius14** [comment]
Were you using previous builds before?

**Comment by sleinert** [comment]
I used your 0.4 build and after I saw your commit from 2 days ago, I built it from source.
